### ISSUE TITLE
[RFE]Display IPolB traffic

### ISSUE THREAD

**Issue by pecameron** [iptraf-ng/iptraf-ng#12]
[RFE] IPoIB: iptraf-ng not showing IPoIB traffic

bug  1140211
https://bugzilla.redhat.com/show_bug.cgi?id=1140211
Description of problem:

While iptraf-ng shows the 'ib0' interface for the IP-over-infiniband link,
no traffic in any of the options is shown

Version-Release number of selected component (if applicable):
iptraf-ng-1.1.4-4.el7.x86_64

Note that /sys/class/net/ib0/statistics/tx_bytes is counting up, so some stats are being produced by the kernel.

How reproducible:
100%

Steps to Reproduce:
1. Take two machines with infiniband (in true infiniband mode not ether)
2. Setup IPoIB
3. Stuff lots of traffic over the IPoIB interface
4. Attempt to watch with iptraf-ng

Actual results:
0 bytes traffic, no flows shown

Expected results:
Lots of traffic shown (or at least the overall bandwidth)

Additional info:
------------------------------------------------------
Dr. David Alan Gilbert 2016-05-03 15:49:56 UTC
I noticed that in IP traffic monitor part when I select a specific interface it does show 'Packets captured' counting up' but 'No TCP entries'
(In reply to Phil Cameron from comment #3)

> Dr. Gilbert,
> Does ifconfig show the counters?

Yes - see the ifconfig below

> Could you run the following:
> cat /etc/sysconfig/network-scripts/ifcfg-ib0

# Tweaked by dgilbert@redhat.com
DEVICE=ib0
TYPE=Infiniband
IPV6INIT=no
IPV6_AUTOCONF=yes
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.27.3
NETMASK=255.255.255.0
ZONE=trusted

> lspci | grep -i infin

that shows nothing, what does show something is:

# lspci | grep -i network
02:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
02:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
04:00.0 Network controller: Mellanox Technologies MT27500 Family [ConnectX-3]

and it's the ConnectX-3 that's the infiniband.

> ifconfig ib0

# ifconfig ib0
ib0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2044
        inet 192.168.27.3  netmask 255.255.255.0  broadcast 192.168.27.255
        inet6 fe80::xxxx:xxxx:xx:xxxx  prefixlen 64  scopeid 0x20<link>
Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8).
        infiniband xx:xx:xx:xx:xx:xx:00:00:00:00:00:00:00:00:00:00:00:00:00:00  txqueuelen 256  (InfiniBand)
        RX packets 2135575008  bytes 4324002978818 (3.9 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 71586638  bytes 131684509746 (122.6 GiB)
        TX errors 0  dropped 4 overruns 0  carrier 0  collisions 0

and I see both the packets/byte rx/tx going up.

> lsmod

Module                  Size  Used by
iscsi_tcp              18333  0 
libiscsi_tcp           25146  1 iscsi_tcp
ebtable_filter         12827  0 
ebtables               30913  1 ebtable_filter
vhost_net              33917  0 
macvtap                22363  1 vhost_net
macvlan                19233  1 macvtap
nf_conntrack_ipv6      18738  148 
nf_defrag_ipv6         34768  1 nf_conntrack_ipv6
xt_mac                 12492  37 
xt_physdev             12587  370 
xt_set                 13181  37 
ip_set_hash_ip         27260  1 
ip_set                 36439  2 ip_set_hash_ip,xt_set
nfnetlink              14606  1 ip_set
veth                   13365  0 
xt_CHECKSUM            12549  1 
tun                    27141  4 vhost_net
ip6table_filter        12815  1 
ip6_tables             27025  1 ip6table_filter
rpcsec_gss_krb5        31477  0 
nfsv4                 496223  1 
dns_resolver           13140  1 nfsv4
nfs                   251485  2 nfsv4
fscache                64987  2 nfs,nfsv4
openvswitch            84573  0 
libcrc32c              12644  1 openvswitch
ipt_REJECT             12541  9 
xt_comment             12504  5 
xt_conntrack           12760  300 
xt_multiport           12798  153 
iptable_filter         12810  1 
iptable_raw            12678  1 
iptable_security       12705  0 
iptable_mangle         12695  1 
ipt_MASQUERADE         12678  3 
nf_nat_masquerade_ipv4    13412  1 ipt_MASQUERADE
iptable_nat            12875  1 
nf_conntrack_ipv4      14862  153 
nf_defrag_ipv4         12729  1 nf_conntrack_ipv4
nf_nat_ipv4            14115  1 iptable_nat
nf_nat                 26146  2 nf_nat_ipv4,nf_nat_masquerade_ipv4
nf_conntrack          105737  6 nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_ipv4,nf_conntrack_ipv6
ip_tables              27240  5 iptable_security,iptable_filter,iptable_mangle,iptable_nat,iptable_raw
xprtrdma               50777  0 
ib_isert               55331  0 
iscsi_target_mod      295398  1 ib_isert
ib_iser                52048  0 
libiscsi               57233  3 libiscsi_tcp,iscsi_tcp,ib_iser
scsi_transport_iscsi    99909  4 iscsi_tcp,ib_iser,libiscsi
ib_srpt                52416  0 
target_core_mod       371914  3 iscsi_target_mod,ib_srpt,ib_isert
ib_srp                 47430  0 
scsi_transport_srp     20725  1 ib_srp
scsi_tgt               20027  1 scsi_transport_srp
rdma_ucm               22569  0 
ib_ucm                 22546  0 
rdma_cm                43697  4 xprtrdma,ib_iser,rdma_ucm,ib_isert
iw_cm                  41842  1 rdma_cm
iTCO_wdt               13480  0 
iTCO_vendor_support    13718  1 iTCO_wdt
ipmi_devintf           17572  0 
intel_powerclamp       18764  0 
coretemp               13435  0 
kvm_intel             162153  0 
kvm                   525259  1 kvm_intel
crct10dif_pclmul       14289  0 
crc32_pclmul           13113  0 
crc32c_intel           22079  1 
ghash_clmulni_intel    13259  0 
aesni_intel            69884  0 
lrw                    13286  1 aesni_intel
gf128mul               14951  1 lrw
glue_helper            13990  1 aesni_intel
raid0                  18018  1 
ablk_helper            13597  1 aesni_intel
cryptd                 20359  3 ghash_clmulni_intel,aesni_intel,ablk_helper
pcspkr                 12718  0 
sb_edac                26877  0 
edac_core              57973  1 sb_edac
lpc_ich                21073  0 
i2c_i801               18134  0 
ioatdma                67758  0 
mfd_core               13435  1 lpc_ich
mei_me                 18646  0 
mei                    82723  1 mei_me
shpchp                 37032  0 
wmi                    19070  0 
ipmi_si                53524  0 
ipmi_msghandler        46609  2 ipmi_devintf,ipmi_si
nfsd                  290596  13 
auth_rpcgss            59314  2 nfsd,rpcsec_gss_krb5
nfs_acl                12837  1 nfsd
lockd                  93572  2 nfs,nfsd
grace                  13288  2 nfsd,lockd
bridge                119560  0 
stp                    12976  1 bridge
llc                    14552  2 stp,bridge
ib_ipoib               91475  0 
ib_cm                  46821  5 rdma_cm,ib_srp,ib_ucm,ib_srpt,ib_ipoib
ib_uverbs              47183  2 ib_ucm,rdma_ucm
ib_umad                22129  0 
sunrpc                300421  35 nfs,nfsd,rpcsec_gss_krb5,auth_rpcgss,lockd,nfsv4,xprtrdma,nfs_acl
uinput                 17625  0 
ext4                  578819  3 
mbcache                14958  1 ext4
jbd2                  102940  1 ext4
mlx4_ib               150769  0 
mlx4_en               107274  0 
ib_sa                  33950  6 rdma_cm,ib_cm,mlx4_ib,ib_srp,rdma_ucm,ib_ipoib
ib_mad                 47817  5 ib_cm,ib_sa,mlx4_ib,ib_srpt,ib_umad
vxlan                  41228  1 mlx4_en
ip6_udp_tunnel         12755  1 vxlan
ib_core                98787  15 rdma_cm,ib_cm,ib_sa,iw_cm,xprtrdma,mlx4_ib,ib_mad,ib_srp,ib_ucm,ib_iser,ib_srpt,ib_umad,ib_uverbs,ib_ipoib,ib_isert
udp_tunnel             13187  1 vxlan
ib_addr                18923  3 rdma_cm,ib_core,rdma_ucm
raid1                  39430  3 
sd_mod                 45497  10 
crc_t10dif             12714  2 target_core_mod,sd_mod
crct10dif_common       12595  2 crct10dif_pclmul,crc_t10dif
mgag200                41467  1 
syscopyarea            12529  1 mgag200
sysfillrect            12701  1 mgag200
sysimgblt              12640  1 mgag200
isci                  137622  0 
drm_kms_helper        124974  1 mgag200
ttm                    93488  1 mgag200
igb                   192584  0 
libsas                 83614  1 isci
ahci                   29907  8 
serio_raw              13462  0 
libahci                32031  1 ahci
scsi_transport_sas     41034  2 isci,libsas
ptp                    19231  2 igb,mlx4_en
drm                   349163  4 ttm,drm_kms_helper,mgag200
mlx4_core             293672  2 mlx4_en,mlx4_ib
pps_core               19106  1 ptp
dca                    15130  2 igb,ioatdma
libata                218730  3 ahci,libahci,libsas
i2c_algo_bit           13413  2 igb,mgag200
i2c_core               40582  6 drm,igb,i2c_i801,drm_kms_helper,mgag200,i2c_algo_bit

> 
> Thanks,
> Phil

Dave

**Comment by vsamel** [comment]
This bug is not public, need to login (which I don't want to). Can you copy it here?

**Comment by pecameron** [comment]
@vsamel  I copied (what I thought was) the useful info out of the bug.

**Comment by vsamel** [comment]
@pecameron I am looking into this: I am improving the capture subcommand of iptraf-ng which should help me/us to resolve this issue. Will send you a PR soon.

**Comment by pecameron** [comment]
@vsamel I think this a matter of dealing with the infiniband header (google is your friend). I quickly looked at it a long time ago and didn't have the time or setup to work on it.

**Comment by vsamel** [comment]
Fixed in #15
