### ISSUE TITLE
iptraf exposes raw memory contents which can result in privilege elevation or data theft/tampering

### ISSUE THREAD

**Issue by pecameron** [iptraf-ng/iptraf-ng#23]
https://bugzilla.redhat.com/show_bug.cgi?id=1842690

iptraf-ng raw memory content exposure in status bar at bottom

Description of problem:
iptraf exposes raw memory contents which can result in privilege elevation or data theft/tampering.

Version-Release number of selected component (if applicable):

iptraf-ng-1.1.4-18.el8.x86_64

How reproducible:

# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.1 (Ootpa)

Running transaction
  Preparing        :                                                        1/1 
  Installing       : iptraf-ng-1.1.4-18.el8.x86_64                          1/1 
  Running scriptlet: iptraf-ng-1.1.4-18.el8.x86_64                          1/1 
  Verifying        : iptraf-ng-1.1.4-18.el8.x86_64                          1/1 
Installed products updated.

Installed:
  iptraf-ng-1.1.4-18.el8.x86_64  

# iptraf-ng

> Filters > IP... > Define new filter...

> Provide any text for description, press Enter
> Press i to insert a new line

> In the IP address field on the source side enter %p %p %p %p %p %p %p %p then press Enter
> Press x
> Select Apply filter
> Choose the filter you created and press Enter

>>>> The status bar at the bottom of the window will display raw memory contents. Example from test:

Error message:
Unable to resolve %p %p %p %p %p %p %p %p                          │
Press a key to continue

Status bar:
Resolving (nil) 0x1 (nil) 0x4 0x3125000000000001 0x7ffc00633231 0x8b51a3419cb2d300 0x770000007c

Happens in RHEL 7 also. RHEL 6 does not have the iptraf-ng package.

Actual results:

>>>> The status bar at the bottom of the window will display raw memory contents. Example from test:

Error message:
Unable to resolve %p %p %p %p %p %p %p %p                          │
Press a key to continue

Status bar (at the bottom):
Resolving (nil) 0x1 (nil) 0x4 0x3125000000000001 0x7ffc00633231 0x8b51a3419cb2d300 0x770000007c

Happens in RHEL 7 also. RHEL 6 does not have the iptraf-ng package.

Expected results:

Status bar should not display raw memory contents

Additional info:

I've checked with secvul on this and their response was as follows:

Note from red Hat:
I looked at this issue in detail and was able to reproduce this at my end. While this is definitely a bug, but may not be really a security flaw. The process runs as root and is dumping bits of its own memory on the screen. If you are able to run a program as root, you may as well as dump your own memory, this only allows attacker to disclose information about its own process and there are no secondary affects to this. It could be a security issue if for example the attacker was able to remotely retrieve contents of the process via some network protocol etc (similar to heartbleed), but not otherwise.

Secvul advised to go ahead and get a bug report open on this regardless in regards to fixing the raw memory being displayed in the status bar. I've attached a screenshot for reference. See status bar at bottom of screenshot.

Note from customer report:

From a CLI session launch iptraf (type yes when prompted)
Select Filters
Select IP...
Select Define new filter
Provide any text for a description and press Enter
Press i to insert a new line
In the IP address field on the source side enter %p %p %p %p %p %p %p %p then press Enter
Press x
Select Apply filter
Choose the filter you created and press Enter
The status bar at the bottom of the window will display raw memory contents

Where are you experiencing the behavior?  What environment?

Red Hat Enterprise Linux 7

When does the behavior occur? Frequently?  Repeatedly?   At certain times?

Only when the iptraf tool is used.

**Comment by pecameron** [comment]
@vsamel what do you think about this?

**Comment by vsamel** [comment]
Fixed in PR #22
