### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by pecameron** [iptraf-ng/iptraf-ng#4]
@vsamel I have created PR 3 with some clean ups to get rid of compiler warnings. Would you like to review the changes? 
I would like to merge the doc branch. Would you be interested in reviewing the changes?
You can fork iptraf-ng and create a PR with your changes.
I am still trying to work out how to get you added to the project.

**Comment by vsamel** [comment]
On Sat, Jan 04, 2020 at 11:21:29AM -0800, Phil Cameron wrote:
> @vsamel I have created PR 3 with some clean ups to get rid of compiler warnings. Would you like to review the changes? 

  I have these cleanups in my pile of changes I sent you before. I think
I changed it more cleanly.

> I would like to merge the doc branch. Would you be interested in reviewing the changes?

  I don't see any commits in doc branch (in iptraf-ng/iptraf-ng) ???
